[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
faktor = "H4URXdsQfSNqKNvZJdNxhKVgeNqHjMtZznF14bDeV64b"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
