[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
faktor = "DpXRoReF48SN7G85tf2QXQzaEisBQWSMmncYdrRngyvB"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
